# Generated by Django 4.1.2 on 2022-11-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
